name: API Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test POST /api/test-post returns 200
        run: |
          set -e
          curl -s -D headers.txt -o /dev/null -X POST https://stratalia.nl/api/test-post -H 'Content-Type: application/json' -d '{}' || true
          cat headers.txt
          if ! grep -E '^HTTP/[0-9\\.]+ 200' headers.txt; then
            echo "Expected 200 OK for /api/test-post" >&2
            exit 1
          fi

      - name: Test POST /api/auth/login-post returns 303 on invalid creds
        run: |
          set -e
          curl -s -D headers.txt -o /dev/null -X POST https://stratalia.nl/api/auth/login-post -H 'Content-Type: application/json' -d '{"email":"invalid@example.com","password":"wrong-pass","redirect_to":"/dashboard"}' || true
          cat headers.txt
          if ! grep -E '^HTTP/[0-9\\.]+ 303' headers.txt; then
            echo "Expected 303 See Other for /api/auth/login-post (invalid creds flow)" >&2
            exit 1
          fi

      - name: Test GET /api/auth/me returns 200
        run: |
          set -e
          curl -s -D headers.txt -o /dev/null https://stratalia.nl/api/auth/me || true
          cat headers.txt
          if ! grep -E '^HTTP/[0-9\\.]+ 200' headers.txt; then
            echo "Expected 200 for /api/auth/me" >&2
            exit 1
          fi

      - name: Test GET /api/admin/monitoring returns 401/403 when unauthenticated
        run: |
          set -e
          curl -s -D headers.txt -o /dev/null https://stratalia.nl/api/admin/monitoring || true
          cat headers.txt
          if grep -E '^HTTP/[0-9\\.]+ 401' headers.txt; then
            exit 0
          fi
          if grep -E '^HTTP/[0-9\\.]+ 403' headers.txt; then
            exit 0
          fi
          echo "Expected 401 or 403 for /api/admin/monitoring when unauthenticated" >&2
          exit 1

name: API Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Test POST /api/test-post
        run: |
          curl -i -X POST https://stratalia.nl/api/test-post \
            -H "Content-Type: application/json" -d '{}' | tee result.txt
          grep "200 OK" result.txt || (echo "Expected 200 OK on /api/test-post" && exit 1)

      - name: Test POST /api/auth/login-post (invalid creds)
        run: |
          curl -i -X POST https://stratalia.nl/api/auth/login-post \
            -H "Content-Type: application/json" \
            -d '{"email":"invalid@example.com","password":"wrong","redirect_to":"/dashboard"}' | tee result.txt
          grep "303 See Other" result.txt || (echo "Expected 303 redirect (even with invalid creds)" && exit 1)

      - name: Test GET /api/auth/me
        run: |
          curl -i https://stratalia.nl/api/auth/me | tee result.txt
          grep "200" result.txt || (echo "Expected 200 on /api/auth/me" && exit 1)
