name: API Tests (after Vercel deploy)

on:
  repository_dispatch:
    types: [vercel-deploy-completed]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test POST /api/test-post returns 200
        run: |
          set -e
          curl -s -D headers.txt -o /dev/null -X POST https://stratalia.nl/api/test-post -H 'Content-Type: application/json' -d '{}' || true
          cat headers.txt
          if ! grep -E '^HTTP/[0-9\\.]+ 200' headers.txt; then
            echo "Expected 200 OK for /api/test-post" >&2
            exit 1
          fi

      - name: Test POST /api/auth/login-post returns 303 on invalid creds
        run: |
          set -e
          curl -s -D headers.txt -o /dev/null -X POST https://stratalia.nl/api/auth/login-post -H 'Content-Type: application/json' -d '{"email":"invalid@example.com","password":"wrong-pass","redirect_to":"/dashboard"}' || true
          cat headers.txt
          if ! grep -E '^HTTP/[0-9\\.]+ 303' headers.txt; then
            echo "Expected 303 See Other for /api/auth/login-post (invalid creds flow)" >&2
            exit 1
          fi

      - name: Test GET /api/auth/me returns 200
        run: |
          set -e
          curl -s -D headers.txt -o /dev/null https://stratalia.nl/api/auth/me || true
          cat headers.txt
          if ! grep -E '^HTTP/[0-9\\.]+ 200' headers.txt; then
            echo "Expected 200 for /api/auth/me" >&2
            exit 1
          fi


